const Menu = [
  {
    id: 1,
    title: "General Consultation",
    zhTitle: "綜合諮詢",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Addressing your college-related questions and charting a strategy going forward.",
    zhCaption: "解答您大學申請的相關問題，並討論申請策略。",
  },
  {
    id: 2,
    title: "College and Major Selection",
    zhTitle: "選校選系",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Building a list of colleges and majors that best suit your academic and personal aspirations.",
    zhCaption: "制定一份符合您學術及個人目標的大學及科系申請名單。",
  },
  {
    id: 3,
    title: "Essay Editing",
    zhTitle: "作文修改",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Crafting a standout admissions or supplementary essay that highlights your strengths and perspectives.",
    zhCaption: "撰寫一篇能夠展現您的優點及觀點的大學申請作文。",
  },
  {
    id: 4,
    title: "Resume Editing",
    zhTitle: "履歷修改",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Crafting a list of academic and extracurricular achievements to reflect your best self on paper.",
    zhCaption: "撰寫一份履歷表，以展現您課內課外最出色的成果。",
  },
  {
    id: 5,
    title: "Extracurricular Planning",
    zhTitle: "課外活動規劃",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Strategizing club, camp, and organizational involvement to enhance your application and development.",
    zhCaption: "規劃您課外活動的參與，以提升您的申請素材及個人發展。",
  },
  {
    id: 6,
    title: "Community Service Planning",
    zhTitle: "社區服務規劃",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Strategizing volunteer opportunities that highlight your passion and commitment.",
    zhCaption: "規劃對您最合適的社區服務，以展現您的興趣及熱誠。",
  },
  {
    id: 7,
    title: "Test and Certification Planning",
    zhTitle: "測驗認證規劃",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Strategizing tests and certifications that best enhance your application and helping you prepare for them.",
    zhCaption: "規劃並協助您準備有效提升申請素材的測驗及認證。",
  },
  {
    id: 8,
    title: "Junior or Senior Package",
    zhTitle: "11或12年級生方案",
    category: "Package",
    zhCategory: "方案",
    price: 9880,
    caption: "Polishing your profile and accentuating your strengths, empowering you to pursue the most suitable university pathways. Includes 40 sessions.",
    zhCaption: "打造一份展現您優點的申請素材，幫您實現最合適的升學道路。包含40小時的諮詢。",
  },
  {
    id: 9,
    title: "Sophomore Package",
    zhTitle: "10年級生方案",
    category: "Package",
    zhCategory: "方案",
    price: 18880,
    caption: "Crafting an outstanding profile through prioritizing your activities and actualizing your goals. Includes 80 sessions.",
    zhCaption: "透過完善的活動規劃及目標制定，幫您打造一份卓越的申請素材。包含80小時的諮詢。",
  },
  {
    id: 10,
    title: "Freshman Package",
    zhTitle: "9年級生方案",
    category: "Package",
    zhCategory: "方案",
    price: 26880,
    caption: "Crafting an outstanding profile through developing your interests and cultivating your unique voice and goals. Includes 120 sessions.",
    zhCaption: "透過培養興趣及發展個人化目標，幫您打造一份卓越的申請素材。包含120小時的諮詢。",
  },
]

export default Menu