const Menu = [
  {
    id: 1,
    title: "General Consultation",
    zhTitle: "綜合諮詢",
    category: "Hourly",
    zhCategory: "小時制",
    price: 100,
    caption: "Addressing your college-related questions and charting a strategy going forward.",
    zhCaption: "解答您大學申請的相關問題，並討論申請策略。",
  },
  {
    id: 2,
    title: "College Selection",
    zhTitle: "選校選系",
    category: "Hourly",
    zhCategory: "小時制",
    price: 100,
    caption: "Building a solid list of colleges that suits your academic and personal aspirations.",
    zhCaption: "制定一份符合您學術及個人目標的大學申請名單。",
  },
  {
    id: 3,
    title: "Essay Editing",
    zhTitle: "作文修改",
    category: "Hourly",
    zhCategory: "小時制",
    price: 100,
    caption: "Crafting a standout admissions or supplementary essay that highlights your strengths and perspectives.",
    zhCaption: "撰寫一篇能夠展現您的優點及觀點的大學申請作文。",
  },
  {
    id: 4,
    title: "Resume Editing",
    zhTitle: "履歷修改",
    category: "Hourly",
    zhCategory: "小時制",
    price: 100,
    caption: "Fine-tuning your academic and extracurricular achievements to reflect your best self on paper.",
    zhCaption: "修改您的履歷表，以展現您課內課外最出色的成果。",
  },
  {
    id: 5,
    title: "Extracurricular Planning",
    zhTitle: "課外活動規劃",
    category: "Hourly",
    zhCategory: "小時制",
    price: 100,
    caption: "Strategizing your club, sport, and organizational involvement to enhance your application and development.",
    zhCaption: "規劃您課外活動的參與，以提升您的申請素材及個人發展。",
  },
  {
    id: 6,
    title: "Community Service Planning",
    zhTitle: "社區服務規劃",
    category: "Hourly",
    zhCategory: "小時制",
    price: 100,
    caption: "Helping you identify volunteer opportunities that highlight your passions and commitment.",
    zhCaption: "幫助您選擇最適合的社區服務，以展現您的興趣及熱誠。",
  },
  {
    id: 7,
    title: "One-Year Package",
    zhTitle: "一年方案",
    category: "Yearly",
    zhCategory: "學年制",
    price: 4880,
    caption: "Includes behind-the-scenes prep and up to 15 online consultation sessions. For 11th or 12th graders.",
    zhCaption: "包含幕後準備和15次的線上諮詢會議。建議11、12年級生採用。",
  },
  {
    id: 8,
    title: "Two-Year Package",
    zhTitle: "兩年方案",
    category: "Yearly",
    zhCategory: "學年制",
    price: 9680,
    caption: "Developing an outstanding profile through behind-the-scenes prep and up to 30 online consultation sessions.",
    zhCaption: "透過幕後準備和30次的線上諮詢會議，幫您打造一份卓越的申請素材。",
  },
  {
    id: 9,
    title: "Four-Year Package",
    zhTitle: "四年方案",
    category: "Yearly",
    zhCategory: "學年制",
    price: 16800,
    caption: "Developing an outstanding profile through behind-the-scenes prep and up to 60 online consultation sessions.",
    zhCaption: "透過幕後準備和60次的線上諮詢會議，幫您打造一份卓越的申請素材。",
  },
]

export default Menu