const Menu = [
  {
    id: 1,
    title: "General Consultation",
    zhTitle: "綜合諮詢",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Addressing your college-related questions and charting a strategy going forward.",
    zhCaption: "解答您大學申請的相關問題，並討論申請策略。",
  },
  {
    id: 2,
    title: "College and Major Selection",
    zhTitle: "選校選系",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Building a list of colleges and majors that best suit your academic and personal aspirations.",
    zhCaption: "制定一份符合您學術及個人目標的大學及科系申請名單。",
  },
  {
    id: 3,
    title: "Essay Editing",
    zhTitle: "作文修改",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Crafting a standout admissions or supplementary essay that highlights your strengths and perspectives.",
    zhCaption: "撰寫一篇能夠展現您的優點及觀點的大學申請作文。",
  },
  {
    id: 4,
    title: "Resume Editing",
    zhTitle: "履歷修改",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Crafting a list of academic and extracurricular achievements to reflect your best self on paper.",
    zhCaption: "撰寫一份履歷表，以展現您課內課外最出色的成果。",
  },
  {
    id: 5,
    title: "Extracurricular Planning",
    zhTitle: "課外活動規劃",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Strategizing club, camp, and organizational involvement to enhance your application and development.",
    zhCaption: "規劃您課外活動的參與，以提升您的申請素材及個人發展。",
  },
  {
    id: 6,
    title: "Community Service Planning",
    zhTitle: "社區服務規劃",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Strategizing volunteer opportunities that highlight your passion and commitment.",
    zhCaption: "規劃對您最合適的社區服務，以展現您的興趣及熱誠。",
  },
  {
    id: 7,
    title: "Test and Certification Planning",
    zhTitle: "測驗認證規劃",
    category: "Session",
    zhCategory: "單次",
    price: 150,
    caption: "Strategizing tests and certifications that best enhance your application and helping you prepare for them.",
    zhCaption: "規劃並協助您準備有效提升申請素材的測驗及認證。",
  },
  {
    id: 8,
    title: "One-Year Package",
    zhTitle: "一年方案",
    category: "Package",
    zhCategory: "方案",
    price: 4980,
    caption: "Developing an outstanding profile through up 40 sessions. For 11th or 12th graders.",
    zhCaption: "包含40小時的諮詢服務。建議11、12年級生採用。",
  },
  {
    id: 9,
    title: "Two-Year Package",
    zhTitle: "兩年方案",
    category: "Package",
    zhCategory: "方案",
    price: 9880,
    caption: "Developing an outstanding profile through up to 80 sessions.",
    zhCaption: "透過80小時的諮詢服務，幫您打造一份卓越的申請素材。",
  },
  {
    id: 10,
    title: "Four-Year Package",
    zhTitle: "四年方案",
    category: "Package",
    zhCategory: "方案",
    price: 18800,
    caption: "Developing an outstanding profile through up to 160 sessions.",
    zhCaption: "透過160小時的諮詢服務，幫您打造一份卓越的申請素材。",
  },
]

export default Menu